Description: | 
  This template creates an EC2 instance and pre-configures it to run TiddlyWiki on NodeJs. 
  !WARNING! You will be billed for the AWS resources used if you create a stack from this template.
  Be sure to review your billing estimates to avoid any nasty surprises!

Parameters:
  InstanceName:
    Description: The name of your EC2 instance
    Type: String
    Default: TiddlyWiki
  InstanceType:
    Description: Choose an instance to host TiddlyWiki on
    Type: String
    Default: t2.nano
    AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
      - t2.small
    ConstraintDescription: must be a valid EC2 instance type.
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances. If there are no options available, head over to EC2 => Key Pairs and create one.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instance
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Resources:
  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable HTTP access via port 8080 + SSH access"
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0      
        FromPort: '8080'
        IpProtocol: tcp
        ToPort: '8080'
      - CidrIp: 0.0.0.0/0      
        FromPort: '80'
        IpProtocol: tcp
        ToPort: '80'
      - CidrIp: !Ref SSHLocation
        FromPort: '22'
        IpProtocol: tcp
        ToPort: '22'
  TiddlyWikiInstance:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - 
          Key: Name
          Value: !Ref InstanceName
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0bbc25e23a7640b9b
      SecurityGroups:
        - !Ref ServerSecurityGroup
      UserData:
        Fn::Base64: |
           #!/bin/bash
           yum update -y
           yum install -y gcc-c++ make
           curl -sL https://rpm.nodesource.com/setup_11.x | sudo -E bash -
           yum install -y nodejs
           npm install -g tiddlywiki
           sudo tiddlywiki wikiwiki --init server
           wget https://raw.githubusercontent.com/Juan007/cloudformation/master/TiddlyWiki/tiddlywikistartup -O /etc/init.d/tiddlywikistartup
           chmod +x /etc/init.d/tiddlywikistartup
           shutdown -r now